- name: подготовка сервера cms
  hosts: apache1.home.education2
  become: yes
  remote_user: vladimir
  tasks:
    - name: проверка доступности серверов
      ansible.builtin.ping:
#    - name: del packeg php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysqlnd
#      package:
#        state: absent
#        name: httpd
    - name: установка репозитория cms
      package:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    - name: разрешение испльзование репозитория
      ansible.builtin.shell: yum-config-manager --enable remi-php73
    - name: установка прикладных пакетов (CentOS)
      package:
        name: "{{ pkg }}"
        state: present
      loop:  
      - php 
      - php-common 
      - php-opcache 
      - php-mcrypt 
      - php-cli 
      - php-gd 
      - php-curl 
      - php-mysqlnd
      #yum install -y php-mysql php-mbstring php-mcrypt php-devel php-xml php-gd
      loop_control:
        loop_var: pkg
    - name: копирование архива 
      ansible.builtin.shell: wget -PO /var/www/html https://wordpress.org/latest.tar.gz; cd /var/www/html/; tar -xzvf latest.tar.gz; chown -R apache:apache /var/www/html/wordpress/; touch /var/www/html/wp-config.php
    #- name: копирование файла настроек на сервер
    #  ansible.builtin.copy:
    #    remote_src: https://wordpress.org/latest.tar.gz
    #    dest: /var/www/html/
#rm -f -R /var/www/html/; 